{
  "name": "Sora-MissionControl",
  "created": "2026-06-19T03:40:25.206025+00:00",
  "description": "Project: Sora-MissionControl",
  "leads": {
    "cloud": "active",
    "biscuit": "active",
    "korra": "active",
    "lelouch": "active",
    "tifa": "active"
  }
}
